edition: 1.0.0

services:
  TensorflowCustomContainer:
    component: fc
    props:
      region: cn-shanghai
      service:
        name: TensorflowCustomContainer
        role: acs:ram::{FC_ACCOUNT}:role/aliyunfcdefaultrole
      function:
        name: tensorflow
        runtime: custom-container
        timeout: 60
        memorySize: 1024
        caPort: 8501
        customContainerConfig:
          image: {FC_DEMO_IMAGE}
        environmentVariables:
          MODEL_NAME: half_plus_two
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST