edition: 1.0.0

services:
  JavaSpringbootCustomContainer:
    component: fc
    props:
      region: cn-shanghai
      service:
        name: JavaSpringbootCustomContainer
        role: acs:ram::{FC_ACCOUNT}:role/aliyunfcdefaultrole
      function:
        name: java-springboot
        runtime: custom-container
        timeout: 60
        memorySize: 1024
        caPort: 8080
        customContainerConfig:
          image: {FC_DEMO_IMAGE}
          Command: '["java", "-jar", "/workspace/target/gs-spring-boot-docker-0.1.0.jar"]'
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT