edition: 1.0.0

services:
  DotNetCustomContainer:
    component: fc
    props:
      region: cn-shanghai
      service:
        name: DotNetCustomContainer
        role: acs:ram::{FC_ACCOUNT}:role/aliyunfcdefaultrole
      function:
        name: weather-forecast
        runtime: custom-container
        timeout: 30
        memorySize: 512
        caPort: 80
        customContainerConfig:
          image: {FC_DEMO_IMAGE}
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
